version: '2.3'
services:
    app:
        image: t4skforce/shinobidocker-nvidia:latest
        runtime: nvidia
        environment:
            - "TZ=Europe/Berlin"
            - "MYSQL_USER=majesticflame"
            - "MYSQL_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=blubsblawoot"
            - "MYSQL_ROOT_USER=root"
            - "EMBEDDEDDB=false"
            - "ADMIN_USER=admin@shinobi.video"
            - "ADMIN_PASSWORD=admin"
            - "CRON_KEY=b59b5c62-57d0-4cd1-b068-a55e5222786f"
            - "PLUGINKEY_MOTION=49ad732d-1a4f-4931-8ab8-d74ff56dac57"
            - "PLUGINKEY_OPENCV=6aa3487d-c613-457e-bba2-1deca10b7f5d"
            - "PLUGINKEY_OPENALPR=SomeOpenALPRkeySoPeopleDontMessWithYourShinobi"
            - "MOTION_HOST=localhost"
            - "MOTION_PORT=8080"
            - "PASSWORD_HASH=sha256"
            - "PRODUCT_TYPE=Pro"
            - "NVIDIA_VISIBLE_DEVICES=all"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./config:/config
            - ./videos:/opt/shinobi/videos
            - ./datadir:/var/lib/mysql:rw
            - /dev/shm/shinobiDockerTemp:/dev/shm/streams
        ports:
            - "8080:8080"